#!/bin/sh


set -e

cd /var/www/html/ \
    && composer install \
    && php artisan key:generate


# first arg is `-f` or `--some-option`
#if [ "${1#-}" != "$1" ]; then
#	set -- php "$@"
#fi

#exec "$@"

exec apache2ctl -DFOREGROUND

